# Generated by Django 4.2.7 on 2023-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='multiple_choice_question',
            field=models.ManyToManyField(to='assessments.multiplechoice'),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='question_image',
            field=models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='matching',
            name='question_image',
            field=models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question_image',
            field=models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='yesorno',
            name='question_image',
            field=models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to=''),
        ),
    ]
