# Generated by Django 4.2.7 on 2023-12-04 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_questionset_multiple_choice_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'text'), (2, 'bool'), (3, 'option'), (4, 'patren')], default=1)),
                ('snippet', models.TextField(blank=True)),
                ('rubic_code', models.IntegerField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, storage='/static/question/images/', upload_to='')),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxonomy.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxonomy.language')),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxonomy.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxonomy.topic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='matching',
            name='course',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='yesorno',
            name='course',
        ),
        migrations.RemoveField(
            model_name='yesorno',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='yesorno',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='yesorno',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='yesorno',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='fill_in_the_blank',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='matching',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='open',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='yes_or_no',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='fill_in_the_blank_question',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='matching_question',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='multiple_choice_question',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='open_question',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='yes_or_no_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FillInTheBlank',
        ),
        migrations.DeleteModel(
            name='Matching',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
        migrations.DeleteModel(
            name='YesOrNo',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='assessments.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='question',
            field=models.ManyToManyField(to='assessments.question'),
        ),
    ]
