# Generated by Django 4.2.7 on 2023-11-18 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_location_role_profile_created_at_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolehistory',
            name='map_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='role_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userrolemaping'),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
