# Generated by Django 4.2.7 on 2023-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_rolehistory_user_notificationpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Email'), (2, 'Sms'), (3, 'Watsapp')], null=True),
        ),
    ]
