# Generated by Django 4.2.7 on 2023-11-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_phone_profile_about_profile_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='status',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='type',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='watsapp',
            field=models.BooleanField(default=False),
        ),
    ]
