# Generated by Django 4.1.3 on 2022-12-01 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, choices=[('APSB', 'APSB'), ('TNSB', 'TNSB'), ('DSERT', 'DSERT'), ('NCERT', 'NCERT'), ('MHSB', 'MHSB'), ('WBSED', 'WBSED'), ('SCERT', 'SCERT'), ('OPEPA', 'OPEPA'), ('UPMSP ', 'UPMSP '), ('JACB', 'JACB'), ('eVidyaloka ', 'eVidyaloka '), ('BSEB', 'BSEB'), ('UBSE', 'UBSE'), ('GSEB', 'GSEB'), ('JKBOSE', 'JKBOSE'), ('CBSE', 'CBSE')], max_length=128, null=True)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('grade', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='static/uploads/images/course')),
                ('availabilityType', models.CharField(choices=[('1', 'Web1.0 Only'), ('2', 'Mobile App only'), ('3', 'All Platforms')], default='3', max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.language')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'running'), (3, 'completed')], default=1)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('program', models.IntegerField(choices=[(0, 'None'), (1, 'Digital Classroom'), (2, 'LFH'), (3, 'Worksheets'), (4, 'Alumni'), (5, 'Digital School')], default=0)),
                ('ay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.ay')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vrm.center')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vrm.course')),
                ('student', models.ManyToManyField(related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Internal'), (2, 'External')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('num_sessions', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrm.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrm.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'waiting'), (2, 'scheduled'), (3, 'completed'), (4, 'rescheduled'), (5, 'started'), (6, 'cancelled'), (7, 'Offline')], default=1)),
                ('video', models.CharField(blank=True, max_length=1024, null=True)),
                ('comment', models.TextField(blank=True, max_length=2048, null=True)),
                ('cancel_reason', models.IntegerField(blank=True, choices=[(1, 'Internet Down School'), (2, 'Power Cut School'), (3, 'Unscheduled leave School'), (4, 'Internet Down Teacher'), (5, 'Power Cut Teacher'), (6, 'Last Minute Dropout Teacher'), (7, 'Communication Issue'), (8, 'Teacher yet to be backfilled'), (9, 'Others')], null=True)),
                ('ts_link', models.CharField(blank=True, max_length=1024)),
                ('used_lesson_plan', models.BooleanField(default=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrm.offering')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vrm.subtopic')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ManyToManyField(blank=True, null=True, to='vrm.topic')),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='vrm.topic'),
        ),
    ]
