# Generated by Django 4.2.7 on 2023-12-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('organization_type', models.IntegerField(choices=[(1, 'Trust'), (2, 'Society'), (3, 'Corporate'), (4, 'Community'), (99, 'Others')], default=99)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Volunteering'), (2, 'Delivery'), (3, 'Funding'), (4, 'Organization Unit'), (5, 'School Admin'), (6, 'Digital')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Process'), (3, 'Hold'), (4, 'Approved'), (99, 'Rejected')], default=1)),
                ('logo', models.FileField(blank=True, null=True, upload_to='static/partner/logo')),
                ('source', models.IntegerField(choices=[(1, 'Website'), (2, 'Social Media'), (99, 'Others')], default=1)),
                ('contactperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_contactpersion', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('pam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pam_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('landline', models.CharField(blank=True, max_length=128, null=True)),
                ('signatory', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_place', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=128, null=True)),
                ('fcra_registration', models.CharField(blank=True, max_length=128, null=True)),
                ('fcra_account', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_type', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_details', to='partner.partner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted')], default=1)),
                ('ay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_funding_history_ay', to='taxonomy.ay')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_funding_history', to='partner.partner')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_funding_history_requested', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
